'use client'

import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Card } from '@/components/ui/card'
import { MessageCircle, FileText, Zap } from 'lucide-react'

export default function Home() {
  interface Message {
    role: 'user' | 'assistant'
    content: string
  }

  const [input, setInput] = useState('')
  const [messages, setMessages] = useState<Message[]>([])
  const [loading, setLoading] = useState(false)
  const [selectedModel, setSelectedModel] = useState<'local' | 'gemini'>('local')
  const [feature, setFeature] = useState<'chat' | 'notes' | 'summarize'>('chat')
  const [file, setFile] = useState<File | null>(null)

  const [titleText, setTitleText] = useState('')
  const [subtitleText, setSubtitleText] = useState('')
  const fullTitle = 'AI Study Assistant using Local LLM'
  const fullSubtitle = 'An intelligent tool for chatting, summarizing, and generating notes'

  useEffect(() => {
    let i = 0
    let j = 0
    let titleTimer: NodeJS.Timeout
    let subTimer: NodeJS.Timeout

    titleTimer = setInterval(() => {
      setTitleText(fullTitle.substring(0, i + 1))
      i++
      if (i > fullTitle.length) {
        clearInterval(titleTimer)
        subTimer = setInterval(() => {
          setSubtitleText(fullSubtitle.substring(0, j + 1))
          j++
          if (j > fullSubtitle.length) clearInterval(subTimer)
        }, 20)
      }
    }, 40)

    return () => {
      clearInterval(titleTimer)
      clearInterval(subTimer)
    }
  }, [])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim() || loading) return

    const userMessage = input.trim()
    setInput('')
    setMessages(prev => [...prev, { role: 'user', content: userMessage + (file ? `\n[Attached File: ${file.name}]` : '') }])

    setLoading(true)
    try {
      let bodyData;
      let headers: HeadersInit = {};

      if (file) {
        bodyData = new FormData()
        bodyData.append('prompt', userMessage)
        bodyData.append('model', selectedModel)
        bodyData.append('feature', feature)
        bodyData.append('file', file)
      } else {
        bodyData = JSON.stringify({ prompt: userMessage, model: selectedModel, feature: feature })
        headers = { 'Content-Type': 'application/json' }
      }

      // Connect to the new Python Flask backend
      const res = await fetch('http://127.0.0.1:5000/generate', {
        method: 'POST',
        headers: headers,
        body: bodyData,
      })
      const data = await res.json()
      if (data.error) {
        setMessages(prev => [...prev, { role: 'assistant', content: 'Error: ' + data.error }])
      } else {
        setMessages(prev => [...prev, { role: 'assistant', content: data.response }])
      }
      setFile(null)
    } catch (error) {
      setMessages(prev => [...prev, { role: 'assistant', content: 'Error connecting to the backend. Ensure Flask is running on port 5000.' }])
    }
    setLoading(false)
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-background via-background to-background">
      <div className="max-w-4xl mx-auto px-4 py-20">
        {/* Header Section */}
        <div className="text-center mb-16 min-h-[160px] flex flex-col justify-center">
          <h1 className="text-5xl md:text-6xl font-bold text-foreground mb-4 text-balance min-h-[60px] md:min-h-[72px]">
            {titleText}
            {titleText.length < fullTitle.length && <span className="animate-pulse">|</span>}
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto text-pretty min-h-[56px]">
            {titleText.length >= fullTitle.length ? subtitleText : ''}
            {titleText.length >= fullTitle.length && subtitleText.length < fullSubtitle.length && (
              <span className="animate-pulse">|</span>
            )}
          </p>
        </div>

        {/* Chat History */}
        {messages.length > 0 && (
          <div className="mb-8 space-y-6">
            {messages.map((msg, idx) => (
              <Card key={idx} className={`p-6 shadow-md border-border/50 ${msg.role === 'user' ? 'bg-primary/5 ml-auto w-[85%] sm:w-[75%]' : 'bg-card mr-auto w-[90%] sm:w-[85%]'}`}>
                <h3 className="font-semibold text-sm text-muted-foreground mb-2">
                  {msg.role === 'user' ? 'You' : 'AI Assistant'}
                </h3>
                {/* whitespace-pre-wrap ensures that line breaks generated by the AI are properly formatted */}
                <div className="text-card-foreground leading-relaxed whitespace-pre-wrap">
                  {msg.content}
                </div>
              </Card>
            ))}
            {loading && (
              <Card className="p-6 shadow-md border-border/50 bg-card mr-auto w-[90%] sm:w-[85%] animate-pulse">
                <h3 className="font-semibold text-sm text-muted-foreground mb-2">AI Assistant</h3>
                <div className="text-card-foreground leading-relaxed">Thinking...</div>
              </Card>
            )}
          </div>
        )}

        {/* Input Section */}
        
        <div className="flex justify-center space-x-2 mb-4">
          <Button 
            variant={feature === 'chat' ? 'default' : 'outline'} 
            onClick={() => setFeature('chat')}
            className={feature === 'chat' ? 'bg-primary text-primary-foreground' : ''}
          >
            Chat
          </Button>
          <Button 
            variant={feature === 'notes' ? 'default' : 'outline'} 
            onClick={() => setFeature('notes')}
            className={feature === 'notes' ? 'bg-primary text-primary-foreground' : ''}
          >
            Notes Generator
          </Button>
          <Button 
            variant={feature === 'summarize' ? 'default' : 'outline'} 
            onClick={() => setFeature('summarize')}
            className={feature === 'summarize' ? 'bg-primary text-primary-foreground' : ''}
          >
            Summarize
          </Button>
        </div>

        <Card className="mb-8 shadow-lg border-border/50 relative">
          <form onSubmit={handleSubmit} className="p-4 sm:p-6">
            <div className="mb-4 flex justify-end items-center space-x-3">
              <label htmlFor="model-select" className="text-sm font-semibold text-muted-foreground">AI Engine:</label>
              <select
                id="model-select"
                value={selectedModel}
                onChange={(e) => setSelectedModel(e.target.value as 'local' | 'gemini')}
                className="bg-card border border-border text-foreground rounded-md px-3 py-1.5 text-sm font-medium outline-none focus:ring-2 focus:ring-primary shadow-sm cursor-pointer transition-colors"
                disabled={loading}
              >
                <option value="local">Local LLM (Ollama)</option>
                <option value="gemini">Gemini API (Cloud)</option>
              </select>
            </div>
            
            <Textarea
              placeholder={feature === 'notes' ? "Ask a question or upload a PDF to generate notes..." : (feature === 'summarize' ? "Ask a question or upload a PDF to summarize..." : "Ask a question or upload a PDF to chat...")}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              className="min-h-[100px] resize-none pb-14 text-foreground placeholder:text-muted-foreground mb-2"
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault()
                  handleSubmit(e as unknown as React.FormEvent)
                }
              }}
            />
            
            <div className="flex items-center absolute bottom-6 left-4 sm:bottom-8 sm:left-6">
              <input 
                type="file" 
                accept="application/pdf"
                onChange={(e) => setFile(e.target.files?.[0] || null)}
                className="text-sm w-48 sm:w-auto file:mr-4 file:py-1 file:px-3 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-primary/10 file:text-primary hover:file:bg-primary/20"
                disabled={loading}
              />
              {file && <span className="text-xs text-muted-foreground ml-2">({(file.size / 1024 / 1024).toFixed(2)} MB)</span>}
            </div>

            <Button
              type="submit"
              disabled={loading || !input.trim()}
              className="absolute bottom-6 right-6 sm:bottom-8 sm:right-8 bg-black hover:bg-black/80 text-white font-semibold transition-colors"
            >
              {loading ? 'Generating...' : 'Send'}
            </Button>
          </form>
        </Card>

        {/* Features & How It Works (Hidden when chatting) */}
        {messages.length === 0 && (
          <>
            <div className="mb-16">
              <h2 className="text-3xl font-bold text-foreground text-center mb-12 text-balance">
            Our Features
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            {/* Feature Card 1 */}
            <Card className="p-8 shadow-md border-border/50 hover:shadow-lg hover:scale-105 transition-all duration-300 group cursor-pointer bg-card">
              <div className="flex justify-center mb-4">
                <div className="p-3 bg-primary/10 rounded-lg group-hover:bg-primary/20 transition-colors">
                  <MessageCircle className="w-8 h-8 text-primary" />
                </div>
              </div>
              <h3 className="text-xl font-bold text-foreground text-center mb-2">Chatbot</h3>
              <p className="text-card-foreground text-center text-sm">
                Interact with AI and get answers instantly
              </p>
            </Card>

            {/* Feature Card 2 */}
            <Card className="p-8 shadow-md border-border/50 hover:shadow-lg hover:scale-105 transition-all duration-300 group cursor-pointer bg-card">
              <div className="flex justify-center mb-4">
                <div className="p-3 bg-secondary/15 rounded-lg group-hover:bg-secondary/25 transition-colors">
                  <FileText className="w-8 h-8 text-secondary font-bold" strokeWidth={2.5} />
                </div>
              </div>
              <h3 className="text-xl font-bold text-foreground text-center mb-2">Notes Generator</h3>
              <p className="text-card-foreground text-center text-sm">
                Generate short and structured notes from any topic
              </p>
            </Card>

            {/* Feature Card 3 */}
            <Card className="p-8 shadow-md border-border/50 hover:shadow-lg hover:scale-105 transition-all duration-300 group cursor-pointer bg-card">
              <div className="flex justify-center mb-4">
                <div className="p-3 bg-accent/15 rounded-lg group-hover:bg-accent/25 transition-colors">
                  <Zap className="w-8 h-8 text-accent font-bold" strokeWidth={2.5} />
                </div>
              </div>
              <h3 className="text-xl font-bold text-foreground text-center mb-2">Text Summarizer</h3>
              <p className="text-card-foreground text-center text-sm">
                Convert long text into concise summaries
              </p>
            </Card>
          </div>
        </div>

        {/* How It Works Section */}
        <div className="mb-12">
          <h2 className="text-3xl font-bold text-foreground text-center mb-12 text-balance">
            How It Works
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            {/* Step 1 */}
            <div className="flex flex-col items-center">
              <div className="w-12 h-12 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-lg font-bold mb-4">
                1
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2">Enter Your Input</h3>
              <p className="text-muted-foreground text-center text-sm">
                Type your question, topic, or text that you want to work with
              </p>
            </div>

            {/* Step 2 */}
            <div className="flex flex-col items-center">
              <div className="w-12 h-12 rounded-full bg-secondary text-secondary-foreground flex items-center justify-center text-lg font-bold mb-4">
                2
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2">AI Processes</h3>
              <p className="text-muted-foreground text-center text-sm">
                Our local LLM analyzes and processes your input intelligently
              </p>
            </div>

            {/* Step 3 */}
            <div className="flex flex-col items-center">
              <div className="w-12 h-12 rounded-full bg-accent text-accent-foreground flex items-center justify-center text-lg font-bold mb-4">
                3
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2">Get Instant Output</h3>
              <p className="text-muted-foreground text-center text-sm">
                Receive clear, structured results instantly
              </p>
            </div>
          </div>
        </div>
          </>
        )}
      </div>

      {/* Footer */}
      <footer className="mt-8 border-t-2 border-foreground/20 bg-gradient-to-t from-muted/10 to-transparent">
        <div className="max-w-4xl mx-auto px-4 py-12 text-center">
          <p className="text-muted-foreground text-sm">
            Created by <span className="font-semibold text-foreground">Ambika</span> in <span className="font-semibold text-foreground">2026</span>
          </p>
        </div>
      </footer>

      <style>{`
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        @keyframes titleFade {
          0% {
            opacity: 0;
            transform: translateY(20px);
          }
          100% {
            opacity: 1;
            transform: translateY(0);
          }
        }

        @keyframes typeWriter {
          0% {
            opacity: 0;
            text-shadow: 0 0 0 rgba(0, 0, 0, 0);
          }
          1% {
            opacity: 1;
          }
          100% {
            opacity: 1;
            text-shadow: 0 0 0 rgba(0, 0, 0, 0);
          }
        }

        @keyframes blink {
          0%, 49% {
            border-right-color: rgba(0, 0, 0, 0.3);
          }
          50%, 100% {
            border-right-color: transparent;
          }
        }

        .animate-fade-in {
          animation: fadeIn 0.6s ease-out;
        }

        .animate-title-fade {
          animation: titleFade 0.8s cubic-bezier(0.34, 1.56, 0.64, 1);
        }

        .animate-title-type {
          animation: typeWriter 1.5s steps(50, end) both;
          border-right: 3px solid;
          border-right-color: transparent;
          white-space: normal;
          overflow: visible;
          display: inline-block;
        }

        .animate-title-type::after {
          content: '';
          animation: blink 0.8s infinite;
          display: inline-block;
          width: 2px;
          height: 1.2em;
          margin-left: 2px;
          background-color: currentColor;
          vertical-align: text-bottom;
        }

        .animate-subtitle-type {
          animation: typeWriter 1.5s steps(60, end) 0.4s both;
          white-space: normal;
          overflow: visible;
        }
      `}</style>
    </main>
  )
}
